# Generated by Django 5.0.6 on 2024-06-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivation',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
