from .registration import RegistrationView
from .forget_password import ForgetPasswordView
from .user import UserDetailView
from .changepassword import ChangePasswordView
from .emailexist import EmailExistAPIView
from .reset_password import ResetPasswordAPIView
from .accountstatus import AccountStatusAPIView
from .accountactivation import AccountActivationAPIView
from .resend_activation import ResendActivationAPIView
